FROM almalinux:9
LABEL author="Lokeshwarrier" \
        project="dockerfile" \
        session="joindevops"
RUN cd /tmp
RUN mkdir /app
WORKDIR /app

RUN echo "the current directory is : $(pwd)"
CMD ["sleep", "100"]
