FROM almalinux:9
LABEL author="Lokeshwarrier" \
        project="dockerfile" \      
    session="joindevops"

ARG course="devops"
    trainer="sivasir"
RUN echo "the course is : ${course},  the trainer is : ${trainer}"


CMD ["sleep", "100"]
