FROM almalinux:9
LABEL author="Lokeshwarrier" \  
      project="dockerfile" \  
      session="joindevops"
ADD https://raw.githubusercontent.com/daws-90s/notes/refs/heads/main/session-03.txt /tmp/
CMD ["sleep", "100"]